#!/bin/bash

echo_=$(which echo)
auth_sock_pattern="/tmp/ssh-*/agent.*"

latest_auth_sock=$(ls -t ${auth_sock_pattern} 2>/dev/null | head -1)
auth_socket_link="${HOME}/.ssh/ssh_auth_sock"

if test -S "${latest_auth_sock}"; then

	$echo_ -e "\n* sshrc: Ssh agent socket link is updated:"

	ln -svf $latest_auth_sock $auth_socket_link

	$echo_

	exit 0
fi

$echo_ -e "\n* sshrc: No ssh agent sockets in \"${auth_sock_pattern}\"\n"
