#!/bin/bash

sock_path="/tmp/ssh-*/agent.*"

if ! test -S ${sock_path}; then
	echo -e "\nNo ssh agent sockets in \"${sock_path}\"\n"
	exit 0
fi

last_auth_socket=$(ls -t /tmp/ssh-*/agent.* | head -1)
auth_socket_link="${HOME}/.ssh/ssh_auth_sock"

echo -e "\nSsh agent socket link is updated:"
ln -svf "$last_auth_socket" $auth_socket_link
echo
